/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Prof.v7x (https://sketchfab.com/profesor_v7x)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dragon-white-low-poly-7b89c3d4718e4131b1ecf169fd05d2ba
Title: Dragon White Low Poly
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

import scene from "../assets/3d/dragon2.glb";

const Dragon2 = ({ currentAnimation, ...props }) => {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF(scene);
    const { actions } = useAnimations(animations, group);

    useEffect(() => {
        //console.log(actions);
        Object.values(actions).forEach((action) => action.stop());

        if (actions[currentAnimation]) {
            const action = actions[currentAnimation];
            if (currentAnimation === "stand") {
                action.timeScale = 0.2;
            }
            action.play();
        }
    }, [actions, currentAnimation]);

    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Sketchfab_Scene">
                <group
                    name="Sketchfab_model"
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={20.612}
                >
                    <group
                        name="zq127_binglong_modefbx"
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.01}
                    >
                        <group name="Object_2">
                            <group name="RootNode">
                                <group name="zq127_binglong_mode" scale={1.5}>
                                    <group name="Object_5">
                                        <primitive object={nodes._rootJoint} />
                                        <skinnedMesh
                                            name="Object_8"
                                            geometry={nodes.Object_8.geometry}
                                            material={
                                                materials.zq127_binglong_1
                                            }
                                            skeleton={nodes.Object_8.skeleton}
                                        />
                                        <group
                                            name="Object_7"
                                            rotation={[-Math.PI / 2, 0, 0]}
                                            scale={1.5}
                                        />
                                        <group
                                            name="zq127_binglong"
                                            rotation={[-Math.PI / 2, 0, 0]}
                                        />
                                    </group>
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    );
};

export default Dragon2;
