/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Prof.v7x (https://sketchfab.com/profesor_v7x)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dragon-boss-a8d48a46c4264148974a7b7c37087e94
Title: Dragon Boss
*/

import { useRef, useEffect } from "react";
import { useAnimations, useGLTF } from "@react-three/drei";

import dragonScene from "../assets/3d/dragon.glb";
import { useFrame } from "@react-three/fiber";

const Dragon = () => {
    const dragonRef = useRef();
    const { scene, animations } = useGLTF(dragonScene);
    const { actions } = useAnimations(animations, dragonRef);

    useEffect(() => {
        actions["run"].play();
    }, []);

    useFrame(({ clock, camera }) => {
        // Update the Y position to simulate bird-like motion using a sine wave
        dragonRef.current.position.y = Math.sin(clock.elapsedTime) * 0.2 + 2;

        if (dragonRef.current.position.x > camera.position.x + 10) {
            // Change direction to backward and rotate the dragon 270 degrees on the y-axis
            dragonRef.current.rotation.y = Math.PI * 1.5;
            dragonRef.current.rotation.x = 1.5;
            dragonRef.current.rotation.z = -0.1;
        } else if (dragonRef.current.position.x < camera.position.x - 10) {
            // Change direction to forward and reset the dragon's rotation
            dragonRef.current.rotation.y = Math.PI;
            dragonRef.current.rotation.x = 0;
            dragonRef.current.rotation.z = 1.5;
        }

        // Update the X and Z positions based on the direction
        if (dragonRef.current.rotation.y === Math.PI) {
            // Moving forward
            dragonRef.current.position.x += 0.01;
            dragonRef.current.position.z -= 0.01;
        } else {
            // Moving backward
            dragonRef.current.position.x -= 0.01;
            dragonRef.current.position.z += 0.01;
        }
    });

    return (
        <mesh
            ref={dragonRef}
            position={[-5, 2, 1]}
            scale={[3, 3, 3]}
            rotation={[0, Math.PI, 1.5]}
        >
            <primitive object={scene} />
        </mesh>
    );
};

export default Dragon;
